import {
    bonBonBumSurtido, coffeeDelightBlando, chicleSplotSandiaAcid, chocolateBlancoAlmendras, chocolateBlancoFresas, chocolateyMacadamia, galletaDeditos, galletaMilo, galletaMorenitas,
} from "../assets"

export const Products = [
    {
        nombre: "Bon Bon Bum Surtido",
        codigo: 10,
        categoria: "Caramelo",
        imagen: bonBonBumSurtido,
        unidadMedida: "24 Und x 456 g",
        descripcion: "Bombón de caramelo redondo relleno de chicle bomba, sabor a Fresa, Fresa Intensa, Lulo y Mandarina.",
        valorCompra: 6400,
        valorVenta: 8600 ,
        sinRebaja: 9000,
        cantidad: 20,
        calificacion:4,
        proveedor: "Colombina",
    },
    {
        nombre: "Coffee Delight Blando",
        codigo: 20,
        categoria: "Caramelo",
        imagen: coffeeDelightBlando,
        unidadMedida: "10 Und x 80 g",
        descripcion: "Caramelo masticable con el aunténtico sabor a café de Coffee Delight Intenso.",
        valorCompra: 6400,
        valorVenta: 12900 ,
        sinRebaja: 16000,
        cantidad: 20,
        calificacion:4,
        proveedor: "Colombina",
    },
    {
        nombre: "Chicle Splot Sandia Acid",
        codigo: 30,
        categoria: "Caramelo",
        imagen: chicleSplotSandiaAcid,
        unidadMedida: "10 Und x 80 g",
        descripcion: "Chicle bomba sabor a sandia con relleno de polvo ácido, presentacion de 50 Unid.",
        valorCompra: 6400,
        valorVenta: 10000,
        sinRebaja: 12000,
        cantidad: 20,
        calificacion:4,
        proveedor: "Colombina",

    },
    {
        nombre: "Chocolate Blanco y almendras",
        codigo: 40,
        categoria: "Chocolates",
        imagen: chocolateBlancoAlmendras,
        unidadMedida: "12 Und x 80 g",
        descripcion: "Chocolate blanco con trozos de almendras.",
        valorCompra: 6400,
        valorVenta: 70000,
        sinRebaja: 80000,
        cantidad: 50,
        calificacion:5,
        proveedor: "Mont Blanc",
    },
    {
        nombre: "Chocolate Blanco con Fresas",
        codigo: 50,
        categoria: "Chocolates",
        imagen: chocolateBlancoFresas,
        unidadMedida: "10 Und x 80 g",
        descripcion: "Chocolate blanco clásico con trozos de fresas ácidas liofilizadas.",
        valorCompra: 6400,
        valorVenta: 87700,
        sinRebaja: 90000,
        cantidad: 50,
        calificacion:5,
        proveedor: "Mont Blanc",
    },
    {
        nombre: "Chocolate y Macadamia",
        codigo: 60,
        categoria: "Chocolates",
        imagen: chocolateyMacadamia,
        unidadMedida: "10 Und x 80 g",
        descripcion: "Chocolate con leche con trozos de almendras y macadamia caramelizada.",
        valorCompra: 6400,
        valorVenta: 83950,
        sinRebaja: 90000,
        cantidad: 50,
        calificacion:5,
        proveedor: "Mont Blanc",
    },
    {
        nombre: "Galleta deditos",
        codigo: 70,        
        categoria: "Galletas",
        imagen: galletaDeditos,
        unidadMedida: "10 Und x 80 g",
        descripcion: "Deliciosa galleta recubierta con sabor a chocolate, son el antojo perfecto que puedes disfrutar en la porcion ideal.",
        valorCompra: 6400,
        valorVenta: 2000,
        sinRebaja: 9890,
        cantidad: 50,
        calificacion:5,
        proveedor: "Nestle",
    },
    {
        nombre: "Galleta milo",
        codigo: 80,
        categoria: "Galletas",
        imagen: galletaMilo,
        unidadMedida: "10 Und x 80 g",
        descripcion: "MILO® sándwich Galleta rellena con crema. Galletas con las que tus hijos pueden disfrutar toda la nutrición, sabor y la energía de MILO®.",
        valorCompra: 6400,
        valorVenta: 8650,
        sinRebaja: 9190,
        cantidad: 50,
        calificacion:5,
        proveedor: "Nestle",
    },
    {
        nombre: "Galleta morenitas",
        codigo: 90,
        categoria: "Galletas",
        imagen: galletaMorenitas,
        unidadMedida: "10 Und x 80 g",
        descripcion: "MORENITAS® son el antojo perfecto que puedes disfrutar en la porción ideal porque son Galletas dulces cubiertas con sabor a chocolate.",
        valorCompra: 6400,
        valorVenta: 9890,
        sinRebaja: 15000,
        cantidad: 50,
        calificacion:5,
        proveedor: "Nestle",
    },
    
]